// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":return img`
...........fffcc....................
...........fbbbbcfffffffff..........
............fbfffbbbbbbbbbf.........
............ffbbbbffb111bbf.........
..........ffcbbbbbff11111bf.........
.........fcccbcbcbb11cccc1f.........
ccccc...fcccbcbcbbb1c1c1cf..........
cbbddccfccccbcbcbbb1333c............
.ccbddbcccccbbbbbbb1c333c...........
..ccbbcccccccbbbbb11c133c...........
..fccbffccccccbbbb111c31cc..........
..fccf.cbbcccccbbbc111111c..........
.fcbbf..cdddddfbbbc1111cc...........
.fbbf....cdddfbbdbffccc.............
fbbf......ccfbbdbf..................
fff.........fffff...................
`;
            case "image3":return img`
........................
........................
........................
........................
..........ffff..........
........ff1111ff........
.......fb111111bf.......
.......f11111111f.......
......fd11111111df......
......fd11111111df......
......fddd1111dddf......
......fbdbfddfbdbf......
......fcdcf11fcdcf......
.......fb111111bf.......
......fffcdb1bdffff.....
....fc111cbfbfc111cf....
....f1b1b1ffff1b1b1f....
....fbfbffffffbfbfbf....
.........ffffff.........
...........fff..........
........................
........................
........................
........................
`;
            case "image2":return img`
. . . . . . . . . . . . . . . . 
. . . . c c c c . . . . . . . . 
. . . c d d d d c c . . . . . . 
. . . c d c c c c c c . . . . . 
. . . c c d 4 4 4 4 c c . . . . 
c c . c 1 4 4 4 4 4 d 4 c . . . 
c 4 c 1 d 4 4 4 4 1 4 4 4 c . . 
c 4 c 1 4 4 4 4 4 1 4 4 4 4 c . 
f 4 4 1 4 4 4 4 4 1 4 4 4 4 4 f 
f 4 f 1 4 4 4 c c 1 4 f 4 4 4 f 
f 4 f d 4 4 f 4 4 1 4 4 4 4 4 f 
f f f f d 4 f 4 c 1 4 4 4 4 f . 
. . c f c 4 f f 4 4 d 4 f f . . 
. . c b d c 4 4 4 4 f f . . . . 
. . c d d d f f f f . . . . . . 
. . . c c c . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
