controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Fish = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . . . c c c c . . . . . . . . 
        . . . c d d d d c c . . . . . . 
        . . . c d c c c c c c . . . . . 
        . . . c c d 4 4 4 4 c c . . . . 
        c c . c 1 4 4 4 4 4 d 4 c . . . 
        c 4 c 1 d 4 4 4 4 1 4 4 4 c . . 
        c 4 c 1 4 4 4 4 4 1 4 4 4 4 c . 
        f 4 4 1 4 4 4 4 4 1 4 4 4 4 4 f 
        f 4 f 1 4 4 4 c c 1 4 f 4 4 4 f 
        f 4 f d 4 4 f 4 4 1 4 4 4 4 4 f 
        f f f f d 4 f 4 c 1 4 4 4 4 f . 
        . . c f c 4 f f 4 4 d 4 f f . . 
        . . c b d c 4 4 4 4 f f . . . . 
        . . c d d d f f f f . . . . . . 
        . . . c c c . . . . . . . . . . 
        `, Shark, 200, 0)
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`transparency16`, function (sprite, location) {
    let mySprite: Sprite = null
    tiles.setTilemap(tilemap`level1`)
    tiles.placeOnRandomTile(mySprite, assets.tile`transparency16`)
    info.startCountdown(10)
    music.wawawawaa.play()
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    Bogey.destroy()
    Bogey.destroy(effects.fire, 100)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    Bogey.destroy()
    info.changeLifeBy(-1)
})
let Bogey: Sprite = null
let Fish: Sprite = null
let Shark: Sprite = null
Shark = sprites.create(img`
    ...........fffcc....................
    ...........fbbbbcfffffffff..........
    ............fbfffbbbbbbbbbf.........
    ............ffbbbbffb111bbf.........
    ..........ffcbbbbbff11111bf.........
    .........fcccbcbcbb11cccc1f.........
    ccccc...fcccbcbcbbb1c1c1cf..........
    cbbddccfccccbcbcbbb1333c............
    .ccbddbcccccbbbbbbb1c333c...........
    ..ccbbcccccccbbbbb11c133c...........
    ..fccbffccccccbbbb111c31cc..........
    ..fccf.cbbcccccbbbc111111c..........
    .fcbbf..cdddddfbbbc1111cc...........
    .fbbf....cdddfbbdbffccc.............
    fbbf......ccfbbdbf..................
    fff.........fffff...................
    `, SpriteKind.Player)
Shark.setStayInScreen(true)
info.setLife(3)
controller.moveSprite(Shark, 200, 200)
game.onUpdateInterval(500, function () {
    Bogey = sprites.create(img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    Bogey.setVelocity(-100, 0)
    Bogey.left = scene.screenWidth()
    Bogey.y = randint(0, scene.screenHeight())
    Bogey.setFlag(SpriteFlag.AutoDestroy, true)
})
